import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { createFlagsmithInstance } from 'flagsmith/isomorphic'
import { Posts } from "./components/posts";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const flagsmith = createFlagsmithInstance();
  const environmentID = process.env.FLAGSMITH_ENVIRONMENT_ID || "";
  await flagsmith.init({
    environmentID,
  });
  const serverState = flagsmith.getState();
  flagsmith.setTrait('posts', 'true')
  return (
    <html lang="en">
      <Providers serverState={serverState}>
        <body className={inter.className}>{children}</body>
      </Providers>
    </html>
  );
}
